import { Navbar } from "@/components/views/root/navbar";
import PreviewOrDevelopmentModal from "@/components/views/root/preview-or-development-modal";
import { ThemeProvider } from "@/provider/theme-provider";
import type { Metadata } from "next";
import { headers } from "next/headers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hostname = (await headers()).get("host");
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {hostname === "localhost:3000" && <PreviewOrDevelopmentModal />}
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
